FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY pyproject.toml .
RUN pip install --no-cache-dir -e .

ENV PYTHONPATH=/app/src
ENV MODEL_URI=artifacts/model

CMD ["uvicorn", "fraud_mlops.api:app", "--host", "0.0.0.0", "--port", "8000"]
